### ISSUE TITLE
End of job

### ISSUE THREAD

**Issue by filiptronicek** [mattd/google-photos-downloader#1]
Hi!
I know it's probably just me being stupid but when I ran the program after 73 downloaded photos it returned:
`Reached end of download job at AIWN3iUw + a couple more random letters`
What do I do now?

**Comment by mattd** [comment]
Hi Filip!

So the way I have this set up, you’re intended to run the script once to get the whole library, and then run it periodically to get only new photos since the last time you ran the download. 

The behavior you saw is what happens when you’re running it a second (or later) time.

If that wasn’t the desired behavior, you can delete the file sync-stop.txt and run the script again. But if you do that, be aware that the script will try to download your entire library again.

If it _was_ the desired behavior, you’re done!

(Also, be aware that if your library is large, there’s a good chance your access token will expire mid download. I haven’t come up with a good solution to that yet.)
